apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
  labels:
    backplaneconfig.name: multiclusterengine
spec:
  controllersConfig:
    default:
      replicas: 1
  argoCDConfig:
    enabled: true
    namespace: openshift-gitops