---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ironic-bmo-configmap
  namespace: metal-provisioner
data:
  IRONIC_FAST_TRACK: 'true'
  DEPLOY_KERNEL_URL: ironic-http-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud/images/ironic-python-agent.kernel
  RESTART_CONTAINER_CERTIFICATE_UPDATED: 'false'
  INSPECTOR_REVERSE_PROXY_SETUP: 'false'
  PROVISIONING_INTERFACE: eth0 # this is the interface on the host node - as Ironic is provide hostnetwork privilege, it will look for this interface to get its IP. Make sure it to update as per your environment.
  PROVISIONING_IP: '10.245.64.35'
  IRONIC_INSPECTOR_URL: ironic-inspector-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud
  IRONIC_KERNEL_PARAMS: console=ttyS0
  IRONIC_API_URL: ironic-api-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud
  DHCP_RANGE: '172.22.0.10,172.22.0.100' # not needed in our case but required by Ironic
  IRONIC_INSPECTOR_VLAN_INTERFACES: all
  IRONIC_ENDPOINT: ironic-api-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud/v1/
  DEPLOY_RAMDISK_URL: ironic-http-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud/images/ironic-python-agent.initramfs
  IRONIC_HTTP_URL: ironic-http-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud
  IRONIC_URL_HOST: ironic-http-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud
  HTTP_PORT: '6180'
  IRONIC_INSPECTOR_ENDPOINT: ironic-inspector-metal-provisioner.rhacm-hub-fringe-sat-b95ece5a8e5f8f2343b2871be9bb6524-0000.au-syd.containers.appdomain.cloud/v1/
  IRONIC_USE_MARIADB: 'true'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ironic-htpasswd
  namespace: metal-provisioner
data:
  HTTP_BASIC_HTPASSWD: 'bob:$2y$05$3.cpdcaJSTH5jbPDA3MjJuxYjmGMEwdv7uHdDCeu7gQnx920i0YOm'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ironic-inspector-htpasswd
  namespace: metal-provisioner
data:
  HTTP_BASIC_HTPASSWD: 'bob:$2y$05$Z6g5zDHDvlflpBCoUFMvJe.9Hdbu0wUpYftkFfOz1020WBVASnY1S'