---
kind: Secret
apiVersion: v1
metadata:
  name: mariadb-password
  namespace: metal-provisioner
data:
  password: Y2hhbmdlbWU=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ironic-auth-config
  namespace: metal-provisioner
data:
  auth-config: W2lyb25pY10KYXV0aF90eXBlPWh0dHBfYmFzaWMKdXNlcm5hbWU9Ym9iCnBhc3N3b3JkPWJvYg==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ironic-inspector-auth-config
  namespace: metal-provisioner
data:
  auth-config: >-
    W2luc3BlY3Rvcl0KYXV0aF90eXBlPWh0dHBfYmFzaWMKdXNlcm5hbWU9Ym9iCnBhc3N3b3JkPWJvYg==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ironic-rpc-auth-config
  namespace: metal-provisioner
data:
  auth-config: >-
    W2pzb25fcnBjXQphdXRoX3R5cGU9aHR0cF9iYXNpYwp1c2VybmFtZT1ib2IKcGFzc3dvcmQ9Ym9iCmh0dHBfYmFzaWNfdXNlcm5hbWU9Ym9iCmh0dHBfYmFzaWNfcGFzc3dvcmQ9Ym9i
type: Opaque