apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

resources:
  - cr.yaml
  - crb.yaml
  - sa.yaml
  - acm-setup.yaml
  - mch-instance.yaml
  - mce-instance.yaml
  - console-link-crb.yaml
  # RHACM console link is only needed for RHACM <2.5
  # - rhacm-console-link.yaml