apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  finalizers:
    - finalizer.multicluster.openshift.io
  labels:
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
  name: multiclusterengine
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  overrides:
    components:
      - enabled: true
        name: assisted-service
      - enabled: true
        name: cluster-lifecycle
      - enabled: true
        name: cluster-manager
      - enabled: true
        name: discovery
      - enabled: true
        name: hive
      - enabled: true
        name: server-foundation
      - enabled: false
        name: managedserviceaccount-preview
      - enabled: true
        name: hypershift-preview
      - enabled: true
        name: console-mce
      - enabled: true
        name: cluster-proxy-addon
      - enabled: true
        name: hypershift-local-hosting
      - enabled: true
        name: local-cluster
  imagePullSecret: multiclusterhub-pull-secret
  targetNamespace: multicluster-engine
  nodeSelector:
    node-role.kubernetes.io/infra: ''
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      operator: Exists