---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalhost-role
  namespace: metal-provisioner
rules:
- apiGroups:
  - coordination.k8s.io
  resources: 
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'