---
kind: Secret
apiVersion: v1
metadata:
  name: ironic-credentials
  namespace: metal-provisioner
data:
  password: Ym9iCg==
  username: Ym9iCg==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: ironic-inspector-credentials
  namespace: metal-provisioner
data:
  password: Ym9iCg==
  username: Ym9iCg==
type: Opaque