apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-wave: "202"
spec:
  advanced:
    rbacQueryProxy:
      replicas: 1
    grafana:
      replicas: 1
    alertmanager:
      replicas: 1
    storeMemcached:
      replicas: 1
    queryFrontendMemcached:
      replicas: 1
    observatoriumAPI:
      replicas: 1
    queryFrontend:
      replicas: 1
    query:
      replicas: 1
    receive:
      replicas: 1
    rule:
      replicas: 1
    store:
      replicas: 1
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret    # The pull secret generated above
  observabilityAddonSpec:               # The ObservabilityAddonSpec defines the global settings for all managed clusters which have observability add-on enabled
    enableMetrics: true                 # EnableMetrics indicates the observability addon push metrics to hub server
    interval: 300                        # Interval for the observability addon push metrics to hub server
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 100Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 100Gi
    ruleStorageSize: 1Gi
    storageClass: ocs-storagecluster-ceph-rbd
    storeStorageSize: 10Gi
  nodeSelector:
    node-role.kubernetes.io/infra:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      operator: Exists