apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap

bases:
  - ../../base

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: ansible-automation-platform-operator
      namespace: aap
    path: patch-channel.yaml