# Allow default sa in multicluster-engine to list out IngressControllers
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-sa-cluster-view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: multicluster-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patcher-cr
