---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patcher-cr
rules:
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - "console.openshift.io"
  resources:
  - consolelinks
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - "operator.openshift.io"
  resources:
  - IngressController
  verbs:
  - get
  - list
  - watch
  - patch
