# Use this if cluster is on OpenStack, bare metal, vSphere or installed using UPI and the platform is None
# https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html-single/clusters/index#enable-cim
# - cim-setup.yaml
# - cr.yaml
# - crb.yaml
# - sa.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - central-infrastructure-management.yaml

resources:
  - ../../base
  - cim-setup.yaml
  - configmap.yaml
  - cr.yaml
  - crb.yaml
  - sa.yaml