---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patcher-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patcher-cr
subjects:
- kind: ServiceAccount
  name: default
  namespace: patch-operator
- kind: ServiceAccount
  name: patch-operator
  namespace: patch-operator